Products Page & Product Detials Page
Thirumathikart/client pull request #10
Opened 2022-10-09 14:24 UTC by DonWick32

- Created Products Page
- Created Product Details Page

2022-10-09 16:40 UTC, Ram-20062003 requested changes

2022-10-09 16:40 UTC, Ram-20062003 commented on lib/views/home.dart
> +// ignore_for_file: prefer_const_constructors
Do not use comments to override the errors . It is not good style of coding. Remove comments and resolve the issue

2022-10-09 16:40 UTC, Ram-20062003 commented on lib/views/home.dart
> +// ignore: import_of_legacy_library_into_null_safe
Same here remove commented lines( the library version is not supporting null safety ,change version)

2022-10-09 16:40 UTC, Ram-20062003 commented on lib/views/product_detail.dart
> +  // ignore: library_private_types_in_public_api
Do not use a stateful widget. instead use controllers. Refer getx package.

2022-10-09 16:40 UTC, Ram-20062003 commented on lib/views/products.dart
> +// ignore_for_file: must_be_immutable, non_constant_identifier_names, use_key_in_widget_constructors, library_private_types_in_public_api, no_logic_in_create_state
same here remove this

2022-10-09 16:40 UTC, Ram-20062003 commented on lib/views/product_detail.dart
> +              '₹ ${product.price}',
Make sure product price changes as it increment and decrement

2022-10-09 16:41 UTC, Ram-20062003 commented on lib/views/products.dart
> +                      Navigator.push(
Use getX here

2022-10-09 16:42 UTC, Ram-20062003 commented on lib/views/products.dart
> +              Navigator.pop(context);
Use getX here

2022-10-09 16:43 UTC, Ram-20062003 commented on lib/views/product_detail.dart
> +              Navigator.pop(context);
Use getx here

2022-10-10 18:16 UTC, Ram-20062003 requested changes

2022-10-10 18:16 UTC, Ram-20062003 commented on lib/controllers/products_controller.dart
> +  final c = 0.obs;
give proper namings here

2022-10-10 18:16 UTC, Ram-20062003 commented on lib/controllers/products_controller.dart
> +  void done() {
here too

2022-10-10 18:16 UTC, Ram-20062003 commented on lib/views/product_detail.dart
> +    final productDetailsController = Get.put(ProductDetailsController());
Do not initalize controller here . create your own bindings and do it. Refer other pages for it.

2022-10-10 18:16 UTC, Ram-20062003 commented on lib/views/products.dart
> +  final productsController = Get.put(ProductsController());
Create a binding for it and initialize controller over there

2022-10-10 18:16 UTC, Ram-20062003 commented on lib/views/products.dart
> +      appBar: AppBar(
use the existing app bar

2022-10-11 10:30 UTC, Ram-20062003 approved these changes

2022-10-11 10:40 UTC, Muhesh7 approved these changes

2022-10-11 10:40 UTC, merged